openapi: 3.2.0
info:
  title: Cloud Foundry V3 Organizations API
  description: '# Welcome to the Experimental Cloud Foundry V3 API Docs!'
  version: latest
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Cloud Foundry
    url: https://www.cloudfoundry.org/
servers:
- url: https://api.example.local
  description: Cloud Foundry V3 API server
security:
- oauth:
  - cloud_controller.read
  - cloud_controller.write
tags:
- name: Organizations
  description: An org is a development account that an individual or multiple collaborators can own and use.
paths:
  /v3/organizations:
    get:
      summary: List organizations
      description: Retrieve all organizations the user has access to.
      operationId: listOrganizations
      tags:
      - Organizations
      parameters:
      - $ref: '#/components/parameters/Page'
      - $ref: '#/components/parameters/PerPage'
      - $ref: '#/components/parameters/OrderBy'
      - $ref: '#/components/parameters/CreatedAts'
      - $ref: '#/components/parameters/UpdatedAts'
      - $ref: '#/components/parameters/LabelSelector'
      - name: names
        in: query
        schema:
          type: array
          items:
            type: string
        description: Comma-delimited list of organization names to filter by
      - name: guids
        in: query
        schema:
          type: array
          items:
            type: string
        description: Comma-delimited list of organization guids to filter by
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationList'
              examples:
                default:
                  summary: default
                  value:
                    pagination:
                      total_results: 2
                      total_pages: 1
                      first:
                        href: https://api.example.org/v3/organizations?page=1&per_page=50
                      last:
                        href: https://api.example.org/v3/organizations?page=1&per_page=50
                      next: null
                      previous: null
                    resources:
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                      created_at: '2017-02-01T01:33:58Z'
                      updated_at: '2017-02-01T01:33:58Z'
                      name: org1
                      suspended: false
                      relationships:
                        quota:
                          data:
                            guid: 123e4567-e89b-12d3-a456-426614174000
                      links:
                        self:
                          href: https://api.example.org/v3/organizations/885735b5-aea4-4cf5-8e44-961af0e41920
                        domains:
                          href: https://api.example.org/v3/organizations/885735b5-aea4-4cf5-8e44-961af0e41920/domains
                        default_domain:
                          href: https://api.example.org/v3/organizations/885735b5-aea4-4cf5-8e44-961af0e41920/domains/default
                        quota:
                          href: https://api.example.org/v3/organization_quotas/b7887f5c-34bb-40c5-9778-577572e4fb2d
                      metadata:
                        labels: {}
                        annotations: {}
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                      created_at: '2017-02-02T00:14:30Z'
                      updated_at: '2017-02-02T00:14:30Z'
                      name: org2
                      suspended: false
                      relationships:
                        quota:
                          data:
                            guid: 123e4567-e89b-12d3-a456-426614174000
                      links:
                        self:
                          href: https://api.example.org/v3/organizations/d4c91047-7b29-4fda-b7f9-04033e5c9c9f
                        domains:
                          href: https://api.example.org/v3/organizations/d4c91047-7b29-4fda-b7f9-04033e5c9c9f/domains
                        default_domain:
                          href: https://api.example.org/v3/organizations/d4c91047-7b29-4fda-b7f9-04033e5c9c9f/domains/default
                        quota:
                          href: https://api.example.org/v3/organization_quotas/b7887f5c-34bb-40c5-9778-577572e4fb2d
                      metadata:
                        labels: {}
                        annotations: {}
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500'
        '502':
          $ref: '#/components/responses/BadGateway'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
    post:
      summary: Create an organization
      description: Create an organization.
      operationId: createOrganization
      tags:
      - Organizations
      requestBody:
        $ref: '#/components/requestBodies/OrganizationCreateRequestBody'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
              examples:
                default:
                  summary: default
                  value:
                    guid: 123e4567-e89b-12d3-a456-426614174000
                    created_at: '2017-02-01T01:33:58Z'
                    updated_at: '2017-02-01T01:33:58Z'
                    name: my-organization
                    suspended: false
                    relationships:
                      quota:
                        data:
                          guid: 123e4567-e89b-12d3-a456-426614174000
                    links:
                      self:
                        href: https://api.example.org/v3/organizations/24637893-3b77-489d-bb79-8466f0d88b52
                      domains:
                        href: https://api.example.org/v3/organizations/24637893-3b77-489d-bb79-8466f0d88b52/domains
                      default_domain:
                        href: https://api.example.org/v3/organizations/24637893-3b77-489d-bb79-8466f0d88b52/domains/default
                      quota:
                        href: https://api.example.org/v3/organization_quotas/b7887f5c-34bb-40c5-9778-577572e4fb2d
                    metadata:
                      labels: {}
                      annotations: {}
          links:
            quota:
              operationId: getOrganizationQuota
              parameters:
                guid: $response.body#/relationships/quota/data/guid
              description: Retrieve the quota associated with this organization
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /v3/organizations/{guid}:
    get:
      summary: Get an organization
      description: This endpoint retrieves the specified organization object.
      operationId: getOrganization
      tags:
      - Organizations
      parameters:
      - $ref: '#/components/parameters/Guid'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
              examples:
                default:
                  summary: default
                  value:
                    guid: 123e4567-e89b-12d3-a456-426614174000
                    created_at: '2017-02-01T01:33:58Z'
                    updated_at: '2017-02-01T01:33:58Z'
                    name: my-organization
                    suspended: false
                    relationships:
                      quota:
                        data:
                          guid: 123e4567-e89b-12d3-a456-426614174000
                    links:
                      self:
                        href: https://api.example.org/v3/organizations/24637893-3b77-489d-bb79-8466f0d88b52
                      domains:
                        href: https://api.example.org/v3/organizations/24637893-3b77-489d-bb79-8466f0d88b52/domains
                      default_domain:
                        href: https://api.example.org/v3/organizations/24637893-3b77-489d-bb79-8466f0d88b52/domains/default
                      quota:
                        href: https://api.example.org/v3/organization_quotas/b7887f5c-34bb-40c5-9778-577572e4fb2d
                    metadata:
                      labels: {}
                      annotations: {}
          links:
            quota:
              operationId: getOrganizationQuota
              parameters:
                guid: $response.body#/relationships/quota/data/guid
                description: Retrieve the quota associated with this organization
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      summary: Update an organization
      description: Update an organization.
      operationId: updateOrganization
      tags:
      - Organizations
      parameters:
      - $ref: '#/components/parameters/Guid'
      requestBody:
        $ref: '#/components/requestBodies/OrganizationUpdateRequestBody'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
              examples:
                default:
                  summary: default
                  value:
                    guid: 123e4567-e89b-12d3-a456-426614174000
                    created_at: '2017-02-01T01:33:58Z'
                    updated_at: '2017-02-01T01:33:58Z'
                    name: my-organization
                    suspended: false
                    relationships:
                      quota:
                        data:
                          guid: 123e4567-e89b-12d3-a456-426614174000
                    links:
                      self:
                        href: https://api.example.org/v3/organizations/24637893-3b77-489d-bb79-8466f0d88b52
                      domains:
                        href: https://api.example.org/v3/organizations/24637893-3b77-489d-bb79-8466f0d88b52/domains
                      default_domain:
                        href: https://api.example.org/v3/organizations/24637893-3b77-489d-bb79-8466f0d88b52/domains/default
                      quota:
                        href: https://api.example.org/v3/organization_quotas/b7887f5c-34bb-40c5-9778-577572e4fb2d
                    metadata:
                      labels: {}
                      annotations: {}
          links:
            quota:
              operationId: getOrganizationQuota
              parameters:
                guid: $response.body#/relationships/quota/data/guid
              description: Retrieve the quota associated with this organization
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
    delete:
      summary: Delete an organization
      description: When an organization is deleted, user roles associated with the organization will also be deleted.
      operationId: deleteOrganization
      tags:
      - Organizations
      parameters:
      - $ref: '#/components/parameters/Guid'
      responses:
        '202':
          description: Accepted
          headers:
            location:
              description: URL of the job to query the asynchronous operation
              schema:
                type: string
                format: uri
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500'
  /v3/organizations/{guid}/domains/default:
    get:
      summary: Get default domain
      description: Retrieve the default domain for a given organization.
      operationId: getDefaultDomainForOrganization
      tags:
      - Organizations
      parameters:
      - $ref: '#/components/parameters/Guid'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
  /v3/organizations/{guid}/usage_summary:
    get:
      summary: Get usage summary
      description: This endpoint retrieves the specified organization object's memory and app instance usage summary.
      operationId: getUsageSummaryForOrganization
      tags:
      - Organizations
      parameters:
      - $ref: '#/components/parameters/Guid'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  usage_summary:
                    type: object
                    properties:
                      started_instances:
                        type: integer
                      memory_in_mb:
                        type: integer
                      routes:
                        type: integer
                      service_instances:
                        type: integer
                      reserved_ports:
                        type: integer
                      domains:
                        type: integer
                      per_app_tasks:
                        type: integer
                      service_keys:
                        type: integer
                  links:
                    type: object
                    properties:
                      self:
                        $ref: '#/components/schemas/Link'
                        description: The URL to get this usage summary
                      organization:
                        $ref: '#/components/schemas/Link'
                        description: The URL to get the organization for this usage summary
              examples:
                default:
                  summary: default
                  value:
                    usage_summary:
                      started_instances: 3
                      memory_in_mb: 50
                      routes: 4
                      service_instances: 2
                      reserved_ports: 1
                      domains: 4
                      per_app_tasks: 2
                      service_keys: 1
                    links:
                      self:
                        href: https://api.example.org/v3/organizations/d4c91047-7b29-4fda-b7f9-04033e5c9c9f/usage_summary
                      organization:
                        href: https://api.example.org/v3/organizations/d4c91047-7b29-4fda-b7f9-04033e5c9c9f
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
  /v3/organizations/{guid}/users:
    get:
      summary: List users for an organization
      description: Retrieve all users with a role in the specified organization.
      operationId: listUsersForOrganization
      tags:
      - Organizations
      parameters:
      - $ref: '#/components/parameters/Guid'
      - $ref: '#/components/parameters/Page'
      - $ref: '#/components/parameters/PerPage'
      - $ref: '#/components/parameters/OrderBy'
      - name: guids
        in: query
        schema:
          type: array
          items:
            type: string
        description: Comma-delimited list of user guids to filter by
      - name: usernames
        in: query
        schema:
          type: array
          items:
            type: string
        description: Comma-delimited list of usernames to filter by
      - name: origins
        in: query
        schema:
          type: array
          items:
            type: string
        description: Comma-delimited list of user origins to filter by
      - name: partial_usernames
        in: query
        schema:
          type: array
          items:
            type: string
        description: Comma-delimited list of partial usernames to filter by
      - $ref: '#/components/parameters/LabelSelector'
      - $ref: '#/components/parameters/CreatedAts'
      - $ref: '#/components/parameters/UpdatedAts'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserList'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
  /v3/organizations/{guid}/relationships/default_isolation_segment:
    get:
      summary: Get default isolation segment
      description: Retrieve the default isolation segment for a given organization.
      operationId: getDefaultIsolationSegmentForOrganization
      tags:
      - Organizations
      parameters:
      - $ref: '#/components/parameters/Guid'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelationshipToOne'
              examples:
                default:
                  summary: default
                  value:
                    data:
                      guid: 123e4567-e89b-12d3-a456-426614174000
                    links:
                      self:
                        href: https://api.example.org/v3/organizations/d4c91047-7b29-4fda-b7f9-04033e5c9c9f/relationships/default_isolation_segment
                      related:
                        href: https://api.example.org/v3/isolation_segments/9d8e007c-ce52-4ea7-8a57-f2825d2c6b39
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      summary: Assign default isolation segment
      description: 'Set the default isolation segment for a given organization. Only isolation segments that are entitled to the organization are eligible to be the default isolation segment.


        Apps will not run in the new default isolation segment until they are restarted.'
      operationId: assignDefaultIsolationSegmentForOrganization
      tags:
      - Organizations
      parameters:
      - $ref: '#/components/parameters/Guid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RelationshipToOne'
            examples:
              default:
                summary: default
                value:
                  data:
                    guid: 123e4567-e89b-12d3-a456-426614174000
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelationshipToOne'
              examples:
                default:
                  summary: default
                  value:
                    data:
                      guid: 123e4567-e89b-12d3-a456-426614174000
                    links:
                      self:
                        href: https://api.example.org/v3/organizations/d4c91047-7b29-4fda-b7f9-04033e5c9c9f/relationships/default_isolation_segment
                      related:
                        href: https://api.example.org/v3/isolation_segments/9d8e007c-ce52-4ea7-8a57-f2825d2c6b39
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
components:
  parameters:
    CreatedAts:
      name: created_ats
      in: query
      required: false
      schema:
        type: string
      description: 'Timestamp to filter by. When filtering on equality, several comma-delimited timestamps may be passed. Also supports filtering with [relational operators](#relational-operators).

        '
      example: '2021-01-01T00:00:00Z'
    Page:
      name: page
      in: query
      required: false
      schema:
        type: integer
      description: Page to display; valid values are integers >= 1
      example: 1
    Guid:
      name: guid
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: The unique identifier for the resource
    PerPage:
      name: per_page
      in: query
      required: false
      schema:
        type: integer
      description: Number of results per page, valid values are 1 through 5000
      example: 50
    OrderBy:
      name: order_by
      in: query
      required: false
      schema:
        type: string
      description: 'Value to sort by. Defaults to ascending; prepend with `-` to sort descending.

        '
      example: created_at
    LabelSelector:
      name: label_selector
      in: query
      description: A query string containing a list of [label selector](#labels-and-selectors) requirements
      required: false
      schema:
        type: string
      example: environment=production
    UpdatedAts:
      name: updated_ats
      in: query
      required: false
      schema:
        type: string
      description: 'Timestamp to filter by. When filtering on equality, several comma-delimited timestamps may be passed. Also supports filtering with [relational operators](#relational-operators).

        '
      example: '2021-01-01T00:00:00Z'
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          description: A numeric code for this error
        detail:
          type: string
          description: Detailed description of the error
        title:
          type: string
          description: Name of the error
    Pagination:
      type: object
      properties:
        total_results:
          type: integer
          description: The total number of results available
        total_pages:
          type: integer
          description: The total number of pages available
        first:
          allOf:
          - $ref: '#/components/schemas/Link'
          - description: The first page of results
        last:
          allOf:
          - $ref: '#/components/schemas/Link'
          - description: The last page of results
        next:
          oneOf:
          - $ref: '#/components/schemas/Link'
          - type: 'null'
          description: The next page of results
        previous:
          oneOf:
          - $ref: '#/components/schemas/Link'
          - type: 'null'
          description: The previous page of results
      description: 'Pagination is a technique used to divide a large set of results into smaller, more manageable sets. This allows clients to retrieve results in smaller chunks, reducing the amount of data transferred and improving performance.

        The pagination object is a JSON object that contains information about the pagination state of the results. It includes the total number of results available, the total number of pages available, and links to the first, last, next, and previous pages of results.

        '
    RelationshipToOne:
      type: object
      properties:
        data:
          type:
          - object
          - 'null'
          $ref: '#/components/schemas/Relationship'
        links:
          type: object
          properties:
            self:
              $ref: '#/components/schemas/Link'
            related:
              $ref: '#/components/schemas/Link'
      description: 'Some relationships relate a resource to exactly one other resource. For example an app can belong to only one space.

        '
    Link:
      type: object
      properties:
        href:
          type: string
          description: The URL of the link
        method:
          type: string
          description: An optional field containing the HTTP method to be used when following the URL
      required:
      - href
      description: 'Each link is keyed by its type and will include a href for the URL and an optional method for links that cannot be followed using GET.

        '
    Metadata:
      type: object
      properties:
        labels:
          type: object
          additionalProperties:
            type:
            - string
            - 'null'
          description: 'A set of key-value pairs that describe the resource. Labels are a JSON object that contains information about a resource. They are used to tag resources with metadata that can be used to filter and group resources. Labels are included in the response body of a request to retrieve a resource.

            Labels are user-specified key/value pairs that are attached to API Resources. They are queryable, identifying attributes of a resource, but they do not affect the operation of CloudFoundry.


            For example, an app may be assigned a label with key sensitive and possible values true or false.


            Users could then find all sensitive apps with a selector for sensitive=true, resulting in a response containing only apps having the label key sensitive with a label value of true.


            Labels

            Labels allow users to apply identifying attributes to resources that are meaningful to the user, but not the CloudFoundry system.


            Examples may include (but are not limited to):


            "production" : "true" or "production" : "false"

            "env" : "dev" or "env" : "test" or "env" : "prod"

            "chargeback-code" : "abc123"

            Label keys

            Label keys are made up of an (optional) prefix, and name. If a prefix is present, it is separated from the name by a /. Prefixes are dns names intended to enable namespacing of label keys.


            A label key prefix must adhere to the following restrictions:


            Length: 0-253 characters

            Allowed characters: alphanumeric ( [a-z0-9A-Z] ), -, and .

            DNS subdomain format (series of subdomain labels separated by .)

            A label key name must adhere to the following restrictions:


            Length: 1-63 characters

            Allowed characters: alphanumeric ( [a-z0-9A-Z] ), -, _, and .

            Must begin and end with an alphanumeric character

            Label values

            Label values must adhere to the following restrictions:


            Length: 0-63 characters

            Allowed characters: alphanumeric ( [a-z0-9A-Z] ), -, _, and .

            Must begin and end with an alphanumeric character

            Empty values are allowed

            '
        annotations:
          type: object
          additionalProperties:
            type:
            - string
            - 'null'
          description: 'A set of key-value pairs that describe the resource. Annotations are a JSON object that contains information about a resource. They are used to tag resources with metadata that can be used to filter and group resources. Annotations are included in the response body of a request to retrieve a resource.

            Annotations are user-specified key-value pairs that are attached to API resources. They do not affect the operation of Cloud Foundry. Annotations cannot be used in filters.


            When a service instance is being created, the service broker is sent the annotations of the service instance, and the space and organization in which the service instance resides. When a service instance is being updated, the service broker is sent the annotations of the space and organization in which the service instance resides. When a service binding is being created, the service broker is sent annotations of any associated app, and the space and organization in which the binding resides. Only annotations with a prefix (e.g. company.com/contacts) are sent to service brokers.


            Examples may include (but are not limited to):


            "contact info": "bob@example.com jane@example.com"

            "library versions": "Spring: 5.1, Redis Client: a184098. yaml parser: 38"

            "git-sha": "d56fe0367554ae5e878e37ed6c5b9a82f5995512"

            Annotation keys

            Annotation keys are made up of an (optional) prefix and name. If a prefix is present, it is separated from the name by a /. Prefixes are DNS names intended to enable namespacing of annotation keys.


            An annotation key prefix must adhere to the following restrictions:


            Length: 0-253 characters

            Allowed characters: a-z, A-Z, 0-9, -, and .; emojis cannot be used in keys

            DNS subdomain format (series of subdomain annotations separated by .)

            An annotation key name must adhere to the following restrictions:


            Length: 1-63 characters

            Allowed characters: a-z, A-Z, 0-9, -, _, and .; emojis cannot be used in keys

            Must begin and end with an alphanumeric character

            Annotation values

            Annotation values must adhere to the following restrictions:


            Length: 0-5000 unicode characters

            '
      description: 'Metadata is a JSON object that contains information about a resource. It includes the GUID of the resource, the time the resource was created, the time the resource was last updated, and links to the resource.

        Metadata is included in the response body of a request to retrieve a resource.

        '
    Relationships:
      type: object
      description: 'Relationships represent associations between resources. When relationships are mutable, they can be used to create, read, update, and delete these associations. An app’s relationship to its current droplet is mutable, but an app’s relationship to its space is not.


        Relationships do not affect the fundamental properties of a resource, but may affect their behavior and permissions logic. Relationships are tied to the lifecycles of the associated resources and will be removed if either of the associated resources are deleted. For example, if a user is removed from an organization, both the user and the organization persist, but the relationship between them does not.


        Not all resources implement every relationship operation demonstrated in the examples below. See the docs for each resource to see how it interacts with its relationships.


        Endpoints that return relationship data list this information under the relationships key.


        The relationship object

        The relationship object is a key-value pair that uniquely identifies a resource. In practice this is almost always the guid of a resource.

        '
    OrganizationList:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        resources:
          type: array
          items:
            $ref: '#/components/schemas/Organization'
      description: A paginated list of organizations
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      description: 'An error response will always return a list of error objects. Errors appear on the job resource for asynchronous operations.

        Clients should use the code and title fields for programmatically handling specific errors. The message in the detail field is subject to change over time.

        '
    Organization:
      type: object
      allOf:
      - $ref: '#/components/schemas/BaseSchema'
      - properties:
          name:
            type: string
            description: Name of the organization
          suspended:
            type: boolean
            description: Whether an organization is suspended or not; non-admins will be blocked from creating, updating, or deleting resources in a suspended organization
          relationships:
            type: object
            properties:
              quota:
                $ref: '#/components/schemas/RelationshipToOne'
            description: The quota applied to the organization
          metadata:
            $ref: '#/components/schemas/Metadata'
          links:
            type: object
            properties:
              self:
                $ref: '#/components/schemas/Link'
                description: The URL to get this organization
              domains:
                $ref: '#/components/schemas/Link'
                description: The URL to get the domains for this organization
              quota:
                $ref: '#/components/schemas/Link'
                description: The URL to get the quota for this organization
              default_domain:
                $ref: '#/components/schemas/Link'
                description: The URL to get the default domain for this organization
      description: 'An org is a development account that an individual or multiple collaborators can own and use. All collaborators access an org with user accounts. Collaborators in an org share a resource quota plan, applications, services availability, and custom domains.

        '
    UserList:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        resources:
          type: array
          items:
            $ref: '#/components/schemas/User'
    BaseSchema:
      type: object
      properties:
        guid:
          type: string
          format: uuid
          description: The unique identifier for the resource
        created_at:
          type: string
          format: date-time
          description: The ISO8601 compatible date and time when resource was created
        updated_at:
          type: string
          format: date-time
          description: The ISO8601 compatible date and time when resource was last updated
      description: 'A resource represents an individual object within the system, such as an app or a service. It is represented as a JSON object.

        A resource consists of several required resource fields and other attributes specific to the resource.

        See Resources and Experimental Resources for specific resources.

        '
    Domain:
      type: object
      allOf:
      - $ref: '#/components/schemas/BaseSchema'
      - properties:
          name:
            type: string
            description: The name of the domain; must be between 3 ~ 253 characters and follow [RFC 1035](https://tools.ietf.org/html/rfc1035)
          internal:
            type: boolean
            description: Whether the domain is used for internal (container-to-container) traffic
          router_group:
            type:
            - object
            - 'null'
            properties:
              guid:
                type: string
                format: uuid
            description: The guid of the desired router group to route `tcp` traffic through; if set, the domain will only be available for `tcp` traffic
          supported_protocols:
            type: array
            items:
              type: string
              enum:
              - http
              - tcp
            description: Available protocols for routes using the domain, currently `http` and `tcp`
          relationships:
            $ref: '#/components/schemas/Relationships'
          metadata:
            $ref: '#/components/schemas/Metadata'
          links:
            type: object
            properties:
              self:
                $ref: '#/components/schemas/Link'
                description: The URL to get this domain
              organization:
                $ref: '#/components/schemas/Link'
                description: The URL to get the organization for this domain
              route_reservations:
                $ref: '#/components/schemas/Link'
                description: The URL to get the route reservations for this domain
              shared_organizations:
                $ref: '#/components/schemas/Link'
                description: The URL to get the shared organizations for this domain
              router_group:
                $ref: '#/components/schemas/Link'
                description: The URL to get the router group for this domain
      description: 'A domain is a fully qualified domain name that is used for application routes. A domain can be scoped to an organization, meaning it can be used to create routes for spaces inside that organization, or be left unscoped to allow all organizations access.

        '
    User:
      type: object
      properties:
        guid:
          type: string
          description: Unique identifier for the user, matching either a UAA user id or client id. A client id may not be a uuid.
        created_at:
          type: string
          format: date-time
          description: The ISO8601 compatible date and time when resource was created
        updated_at:
          type: string
          format: date-time
          description: The ISO8601 compatible date and time when resource was last updated
        username:
          type:
          - string
          - 'null'
          description: The username of the user
        presentation_name:
          type: string
          description: The presentation name of the user
        origin:
          type:
          - string
          - 'null'
          description: The origin of the user
        metadata:
          $ref: '#/components/schemas/Metadata'
        links:
          type: object
          properties:
            self:
              $ref: '#/components/schemas/Link'
              description: The URL to get this user
    Relationship:
      type: object
      properties:
        guid:
          type: string
          format: uuid
          description: The GUID of the resource
  responses:
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    BadGateway:
      description: Bad Gateway
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    ServiceUnavailable:
      description: Service Unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    UnprocessableEntity:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
        text/html:
          schema:
            type: string
  requestBodies:
    OrganizationUpdateRequestBody:
      description: Organization object that needs to be updated
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                description: Organization name
              suspended:
                type: boolean
                description: Whether an organization is suspended or not
              metadata:
                $ref: '#/components/schemas/Metadata'
            description: Request schema for updating an organization
          examples:
            default:
              summary: default
              value:
                name: my-organization
    OrganizationCreateRequestBody:
      description: Organization object that needs to be created
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                description: Organization name
              suspended:
                type: boolean
                description: Whether an organization is suspended or not
              metadata:
                $ref: '#/components/schemas/Metadata'
            required:
            - name
            description: Request schema for creating an organization
          examples:
            default:
              summary: default
              value:
                name: my-organization
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://uaa.cloudfoundry.local/api-oauth/dialog
          scopes:
            cloud_controller.admin: This scope provides read and write access to all resources
            cloud_controller.admin_read_only: This scope provides read only access to all resources
            cloud_controller.global_auditor: This scope provides read access to all resources
            cloud_controller.read: Read access to the Cloud Controller
            cloud_controller.write: Write access to the Cloud Controller
            cloud_controller.update_build_state: This scope allows its bearer to update the state of a build; currently only used when updating builds
            cloud_controller_service_permissions.read: This scope provides read only access for service instance permissions
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearer JWT token authentication
