openapi: 3.2.0
info:
  title: Cloud Foundry V3 Isolation Segments API
  description: '# Welcome to the Experimental Cloud Foundry V3 API Docs!'
  version: latest
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Cloud Foundry
    url: https://www.cloudfoundry.org/
servers:
- url: https://api.example.local
  description: Cloud Foundry V3 API server
security:
- oauth:
  - cloud_controller.read
  - cloud_controller.write
tags:
- name: Isolation Segments
  description: Isolation Segments provide dedicated pools of resources to which apps can be deployed to isolate workloads.
paths:
  /v3/isolation_segments:
    get:
      summary: List isolation segments
      description: Retrieves all isolation segments to which the user has access. For admin, this is all the isolation segments in the system. For anyone else, this is the isolation segments in the allowed list for any organization to which the user belongs.
      operationId: listIsolationSegments
      tags:
      - Isolation Segments
      parameters:
      - $ref: '#/components/parameters/Page'
      - $ref: '#/components/parameters/PerPage'
      - $ref: '#/components/parameters/OrderBy'
      - $ref: '#/components/parameters/CreatedAts'
      - $ref: '#/components/parameters/UpdatedAts'
      - $ref: '#/components/parameters/LabelSelector'
      - name: guids
        in: query
        schema:
          type: array
          items:
            type: string
        description: Comma-delimited list of isolation segment guids to filter by.
      - name: names
        in: query
        schema:
          type: array
          items:
            type: string
        description: Comma-delimited list of isolation segment names to filter by.
      - name: organization_guids
        in: query
        schema:
          type: array
          items:
            type: string
        description: Comma-delimited list of organization guids to filter by.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IsolationSegmentList'
              examples:
                default:
                  summary: default
                  value:
                    pagination:
                      total_results: 11
                      total_pages: 3
                      first:
                        href: https://api.example.org/v3/isolation_segments?page=1&per_page=5
                      last:
                        href: https://api.example.org/v3/isolation_segments?page=3&per_page=5
                      next:
                        href: https://api.example.org/v3/isolation_segments?page=2&per_page=5
                      previous: null
                    resources:
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                      name: an_isolation_segment
                      created_at: '2016-10-19T20:25:04Z'
                      updated_at: '2016-11-08T16:41:26Z'
                      links:
                        self:
                          href: https://api.example.org/v3/isolation_segments/b19f6525-cbd3-4155-b156-dc0c2a431b4c
                        organizations:
                          href: https://api.example.org/v3/isolation_segments/b19f6525-cbd3-4155-b156-dc0c2a431b4c/organizations
                      metadata:
                        annotations: {}
                        labels: {}
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                      name: an_isolation_segment1
                      created_at: '2016-10-19T20:29:19Z'
                      updated_at: '2016-11-08T16:41:26Z'
                      links:
                        self:
                          href: https://api.example.org/v3/isolation_segments/68d54d31-9b3a-463b-ba94-e8e4c32edbac
                        organizations:
                          href: https://api.example.org/v3/isolation_segments/68d54d31-9b3a-463b-ba94-e8e4c32edbac/organizations
                      metadata:
                        annotations: {}
                        labels: {}
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                      name: an_isolation_segment2
                      created_at: '2016-10-19T20:29:22Z'
                      updated_at: '2016-11-08T16:41:26Z'
                      links:
                        self:
                          href: https://api.example.org/v3/isolation_segments/ecdc67c3-a71e-43ff-bddf-048930b8cd03
                        organizations:
                          href: https://api.example.org/v3/isolation_segments/ecdc67c3-a71e-43ff-bddf-048930b8cd03/organizations
                      metadata:
                        annotations: {}
                        labels: {}
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                      name: an_isolation_segment3
                      created_at: '2016-10-19T20:29:27Z'
                      updated_at: '2016-11-08T16:41:26Z'
                      links:
                        self:
                          href: https://api.example.org/v3/isolation_segments/424c89e4-4353-46b7-9bf4-f90bd9bacac0
                        organizations:
                          href: https://api.example.org/v3/isolation_segments/424c89e4-4353-46b7-9bf4-f90bd9bacac0/organizations
                      metadata:
                        annotations: {}
                        labels: {}
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                      name: an_isolation_segment4
                      created_at: '2016-10-19T20:29:33Z'
                      updated_at: '2016-11-08T16:41:26Z'
                      links:
                        self:
                          href: https://api.example.org/v3/isolation_segments/0a79fcec-a648-4eb8-a6c3-2b5be39047c7
                        organizations:
                          href: https://api.example.org/v3/isolation_segments/0a79fcec-a648-4eb8-a6c3-2b5be39047c7/organizations
                      metadata:
                        annotations: {}
                        labels: {}
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500'
        '502':
          $ref: '#/components/responses/BadGateway'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
    post:
      summary: Create an isolation segment
      description: Create an isolation segment.
      operationId: createIsolationSegment
      tags:
      - Isolation Segments
      requestBody:
        $ref: '#/components/requestBodies/IsolationSegmentCreate'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IsolationSegment'
              examples:
                default:
                  summary: default
                  value:
                    guid: 123e4567-e89b-12d3-a456-426614174000
                    name: an_isolation_segment
                    created_at: '2016-10-19T20:25:04Z'
                    updated_at: '2016-11-08T16:41:26Z'
                    links:
                      self:
                        href: https://api.example.org/v3/isolation_segments/b19f6525-cbd3-4155-b156-dc0c2a431b4c
                      organizations:
                        href: https://api.example.org/v3/isolation_segments/b19f6525-cbd3-4155-b156-dc0c2a431b4c/organizations
                    metadata:
                      annotations: {}
                      labels: {}
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /v3/isolation_segments/{guid}:
    get:
      summary: Get an isolation segment
      description: Retrieve an isolation segment to which the user has access. For admin, this is any isolation segment in the system. For anyone else, this is an isolation segment in the allowed list for any organization to which the user belongs.
      operationId: getIsolationSegment
      tags:
      - Isolation Segments
      parameters:
      - $ref: '#/components/parameters/Guid'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IsolationSegment'
              examples:
                default:
                  summary: default
                  value:
                    guid: 123e4567-e89b-12d3-a456-426614174000
                    name: an_isolation_segment
                    created_at: '2016-10-19T20:25:04Z'
                    updated_at: '2016-11-08T16:41:26Z'
                    links:
                      self:
                        href: https://api.example.org/v3/isolation_segments/b19f6525-cbd3-4155-b156-dc0c2a431b4c
                      organizations:
                        href: https://api.example.org/v3/isolation_segments/b19f6525-cbd3-4155-b156-dc0c2a431b4c/organizations
                    metadata:
                      annotations: {}
                      labels: {}
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      summary: Update an isolation segment
      description: Update an isolation segment.
      operationId: updateIsolationSegment
      tags:
      - Isolation Segments
      parameters:
      - $ref: '#/components/parameters/Guid'
      requestBody:
        description: Isolation segment to update
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the isolation segment
                metadata:
                  $ref: '#/components/schemas/Metadata'
            examples:
              default:
                summary: default
                value:
                  name: my_isolation_segment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IsolationSegment'
              examples:
                default:
                  summary: default
                  value:
                    guid: 123e4567-e89b-12d3-a456-426614174000
                    name: <%= name %>
                    created_at: '2016-10-19T20:25:04Z'
                    updated_at: '2016-11-08T16:41:26Z'
                    links:
                      self:
                        href: https://api.example.org/v3/isolation_segments/b19f6525-cbd3-4155-b156-dc0c2a431b4c
                      organizations:
                        href: https://api.example.org/v3/isolation_segments/b19f6525-cbd3-4155-b156-dc0c2a431b4c/organizations
                    metadata:
                      annotations: {}
                      labels: {}
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
    delete:
      summary: Delete an isolation segment
      description: An isolation segment cannot be deleted if it is entitled to any organization.
      operationId: deleteIsolationSegment
      tags:
      - Isolation Segments
      parameters:
      - $ref: '#/components/parameters/Guid'
      responses:
        '204':
          description: No Content
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500'
  /v3/isolation_segments/{guid}/relationships/organizations:
    post:
      summary: Entitle organizations for isolation segment
      description: This endpoint entitles the specified organizations for the isolation segment. In the case where the specified isolation segment is the system-wide shared segment, and if an organization is not already entitled for any other isolation segment, then the shared isolation segment automatically gets assigned as the default for that organization.
      operationId: entitleOrganizationsForIsolationSegment
      tags:
      - Isolation Segments
      parameters:
      - $ref: '#/components/parameters/Guid'
      requestBody:
        description: List of organizations to entitle
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RelationshipToMany'
            examples:
              default:
                summary: default
                value:
                  data:
                  - guid: 123e4567-e89b-12d3-a456-426614174000
                  - guid: 123e4567-e89b-12d3-a456-426614174000
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelationshipToMany'
              examples:
                default:
                  summary: default
                  value:
                    data:
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                    links:
                      self:
                        href: https://api.example.org/v3/isolation_segments/bdeg4371-cbd3-4155-b156-dc0c2a431b4c/relationships/organizations
                      related:
                        href: https://api.example.org/v3/isolation_segments/bdeg4371-cbd3-4155-b156-dc0c2a431b4c/organizations
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
    get:
      summary: List organizations relationship
      description: This endpoint lists the organizations entitled for the isolation segment. For an Admin, this will list all entitled organizations in the system. For any other user, this will list only the entitled organizations to which the user belongs.
      operationId: listOrganizationsForIsolationSegment
      tags:
      - Isolation Segments
      parameters:
      - $ref: '#/components/parameters/Guid'
      - $ref: '#/components/parameters/Page'
      - $ref: '#/components/parameters/PerPage'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelationshipToMany'
              examples:
                default:
                  summary: default
                  value:
                    data:
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                    links:
                      self:
                        href: https://api.example.org/v3/isolation_segments/bdeg4371-cbd3-4155-b156-dc0c2a431b4c/relationships/organizations
                      related:
                        href: https://api.example.org/v3/isolation_segments/bdeg4371-cbd3-4155-b156-dc0c2a431b4c/organizations
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
  /v3/isolation_segments/{guid}/relationships/organizations/{org_guid}:
    delete:
      summary: Revoke entitlement to isolation segment for an organization
      description: This endpoint revokes the entitlement for the specified organization to the isolation segment. If the isolation segment is assigned to a space within an organization, the entitlement cannot be revoked. If the isolation segment is the organization’s default, the entitlement cannot be revoked.
      operationId: revokeIsolationSegmentForOrganization
      tags:
      - Isolation Segments
      parameters:
      - $ref: '#/components/parameters/Guid'
      - name: org_guid
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: The GUID of the organization to revoke entitlement from.
      responses:
        '204':
          description: No Content
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
  /v3/isolation_segments/{guid}/relationships/spaces:
    get:
      summary: List spaces relationship
      description: This endpoint lists the spaces to which the isolation segment is assigned. For an Admin, this will list all associated spaces in the system. For an org manager, this will list only those associated spaces belonging to orgs for which the user is a manager. For any other user, this will list only those associated spaces to which the user has access.
      operationId: listSpacesForIsolationSegment
      tags:
      - Isolation Segments
      parameters:
      - $ref: '#/components/parameters/Guid'
      - $ref: '#/components/parameters/Page'
      - $ref: '#/components/parameters/PerPage'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelationshipToMany'
              examples:
                default:
                  summary: default
                  value:
                    data:
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                    links:
                      self:
                        href: https://api.example.org/v3/isolation_segments/bdeg4371-cbd3-4155-b156-dc0c2a431b4c/relationships/spaces
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
  /v3/isolation_segments/{guid}/organizations:
    get:
      summary: List organizations for isolation segment
      description: This endpoint lists the organizations entitled for the isolation segment. For an Admin, this will list all entitled organizations in the system. For any other user, this will list only the entitled organizations to which the user belongs.
      operationId: listOrganizationsForIsolationSegmentShort
      tags:
      - Isolation Segments
      parameters:
      - $ref: '#/components/parameters/Guid'
      - $ref: '#/components/parameters/Page'
      - $ref: '#/components/parameters/PerPage'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationList'
              examples:
                default:
                  summary: default
                  value:
                    pagination:
                      total_results: 2
                      total_pages: 1
                      first:
                        href: https://api.example.org/v3/isolation_segments/933b4c58-120b-499a-b85d-4b6fc9e2903b/organizations?page=1&per_page=50
                      last:
                        href: https://api.example.org/v3/isolation_segments/933b4c58-120b-499a-b85d-4b6fc9e2903b/organizations?page=1&per_page=50
                      next: null
                      previous: null
                    resources:
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                      created_at: '2017-02-01T01:33:58Z'
                      updated_at: '2017-02-01T01:33:58Z'
                      name: org1
                      suspended: false
                      links:
                        self:
                          href: https://api.example.org/v3/organizations/885735b5-aea4-4cf5-8e44-961af0e41920
                        domains:
                          href: https://api.example.org/v3/organizations/885735b5-aea4-4cf5-8e44-961af0e41920/domains
                        default_domain:
                          href: https://api.example.org/v3/organizations/885735b5-aea4-4cf5-8e44-961af0e41920/domains/default
                        quota:
                          href: https://api.example.org/v3/organization_quotas/b7887f5c-34bb-40c5-9778-577572e4fb2d
                      relationships:
                        quota:
                          data:
                            guid: 123e4567-e89b-12d3-a456-426614174000
                      metadata:
                        labels: {}
                        annotations: {}
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                      created_at: '2017-02-02T00:14:30Z'
                      updated_at: '2017-02-02T00:14:30Z'
                      name: org2
                      suspended: false
                      relationships:
                        quota:
                          data:
                            guid: 123e4567-e89b-12d3-a456-426614174000
                      links:
                        self:
                          href: https://api.example.org/v3/organizations/d4c91047-7b29-4fda-b7f9-04033e5c9c9f
                        domains:
                          href: https://api.example.org/v3/organizations/d4c91047-7b29-4fda-b7f9-04033e5c9c9f/domains
                        default_domain:
                          href: https://api.example.org/v3/organizations/d4c91047-7b29-4fda-b7f9-04033e5c9c9f/domains/default
                        quota:
                          href: https://api.example.org/v3/organization_quotas/b7887f5c-34bb-40c5-9778-577572e4fb2d
                      metadata:
                        labels: {}
                        annotations: {}
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
components:
  schemas:
    Pagination:
      type: object
      properties:
        total_results:
          type: integer
          description: The total number of results available
        total_pages:
          type: integer
          description: The total number of pages available
        first:
          allOf:
          - $ref: '#/components/schemas/Link'
          - description: The first page of results
        last:
          allOf:
          - $ref: '#/components/schemas/Link'
          - description: The last page of results
        next:
          oneOf:
          - $ref: '#/components/schemas/Link'
          - type: 'null'
          description: The next page of results
        previous:
          oneOf:
          - $ref: '#/components/schemas/Link'
          - type: 'null'
          description: The previous page of results
      description: 'Pagination is a technique used to divide a large set of results into smaller, more manageable sets. This allows clients to retrieve results in smaller chunks, reducing the amount of data transferred and improving performance.

        The pagination object is a JSON object that contains information about the pagination state of the results. It includes the total number of results available, the total number of pages available, and links to the first, last, next, and previous pages of results.

        '
    RelationshipToMany:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Relationship'
        links:
          type: object
          properties:
            self:
              $ref: '#/components/schemas/Link'
            related:
              $ref: '#/components/schemas/Link'
      description: 'Some relationships relate a resource to several other resources. For example, an isolation segment can be entitled to multiple organizations.

        '
    IsolationSegment:
      type: object
      allOf:
      - $ref: '#/components/schemas/BaseSchema'
      - properties:
          name:
            type: string
            description: The name of the isolation segment
          metadata:
            $ref: '#/components/schemas/Metadata'
          links:
            type: object
            properties:
              self:
                $ref: '#/components/schemas/Link'
                description: The URL to get this isolation segment
              organizations:
                $ref: '#/components/schemas/Link'
                description: The URL to get the organizations for this isolation segment
      description: An isolation segment provides a dedicated pool of compute resources for an organization or space.
    Link:
      type: object
      properties:
        href:
          type: string
          description: The URL of the link
        method:
          type: string
          description: An optional field containing the HTTP method to be used when following the URL
      required:
      - href
      description: 'Each link is keyed by its type and will include a href for the URL and an optional method for links that cannot be followed using GET.

        '
    RelationshipToOne:
      type: object
      properties:
        data:
          type:
          - object
          - 'null'
          $ref: '#/components/schemas/Relationship'
        links:
          type: object
          properties:
            self:
              $ref: '#/components/schemas/Link'
            related:
              $ref: '#/components/schemas/Link'
      description: 'Some relationships relate a resource to exactly one other resource. For example an app can belong to only one space.

        '
    IsolationSegmentList:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        resources:
          type: array
          items:
            $ref: '#/components/schemas/IsolationSegment'
    Organization:
      type: object
      allOf:
      - $ref: '#/components/schemas/BaseSchema'
      - properties:
          name:
            type: string
            description: Name of the organization
          suspended:
            type: boolean
            description: Whether an organization is suspended or not; non-admins will be blocked from creating, updating, or deleting resources in a suspended organization
          relationships:
            type: object
            properties:
              quota:
                $ref: '#/components/schemas/RelationshipToOne'
            description: The quota applied to the organization
          metadata:
            $ref: '#/components/schemas/Metadata'
          links:
            type: object
            properties:
              self:
                $ref: '#/components/schemas/Link'
                description: The URL to get this organization
              domains:
                $ref: '#/components/schemas/Link'
                description: The URL to get the domains for this organization
              quota:
                $ref: '#/components/schemas/Link'
                description: The URL to get the quota for this organization
              default_domain:
                $ref: '#/components/schemas/Link'
                description: The URL to get the default domain for this organization
      description: 'An org is a development account that an individual or multiple collaborators can own and use. All collaborators access an org with user accounts. Collaborators in an org share a resource quota plan, applications, services availability, and custom domains.

        '
    Metadata:
      type: object
      properties:
        labels:
          type: object
          additionalProperties:
            type:
            - string
            - 'null'
          description: 'A set of key-value pairs that describe the resource. Labels are a JSON object that contains information about a resource. They are used to tag resources with metadata that can be used to filter and group resources. Labels are included in the response body of a request to retrieve a resource.

            Labels are user-specified key/value pairs that are attached to API Resources. They are queryable, identifying attributes of a resource, but they do not affect the operation of CloudFoundry.


            For example, an app may be assigned a label with key sensitive and possible values true or false.


            Users could then find all sensitive apps with a selector for sensitive=true, resulting in a response containing only apps having the label key sensitive with a label value of true.


            Labels

            Labels allow users to apply identifying attributes to resources that are meaningful to the user, but not the CloudFoundry system.


            Examples may include (but are not limited to):


            "production" : "true" or "production" : "false"

            "env" : "dev" or "env" : "test" or "env" : "prod"

            "chargeback-code" : "abc123"

            Label keys

            Label keys are made up of an (optional) prefix, and name. If a prefix is present, it is separated from the name by a /. Prefixes are dns names intended to enable namespacing of label keys.


            A label key prefix must adhere to the following restrictions:


            Length: 0-253 characters

            Allowed characters: alphanumeric ( [a-z0-9A-Z] ), -, and .

            DNS subdomain format (series of subdomain labels separated by .)

            A label key name must adhere to the following restrictions:


            Length: 1-63 characters

            Allowed characters: alphanumeric ( [a-z0-9A-Z] ), -, _, and .

            Must begin and end with an alphanumeric character

            Label values

            Label values must adhere to the following restrictions:


            Length: 0-63 characters

            Allowed characters: alphanumeric ( [a-z0-9A-Z] ), -, _, and .

            Must begin and end with an alphanumeric character

            Empty values are allowed

            '
        annotations:
          type: object
          additionalProperties:
            type:
            - string
            - 'null'
          description: 'A set of key-value pairs that describe the resource. Annotations are a JSON object that contains information about a resource. They are used to tag resources with metadata that can be used to filter and group resources. Annotations are included in the response body of a request to retrieve a resource.

            Annotations are user-specified key-value pairs that are attached to API resources. They do not affect the operation of Cloud Foundry. Annotations cannot be used in filters.


            When a service instance is being created, the service broker is sent the annotations of the service instance, and the space and organization in which the service instance resides. When a service instance is being updated, the service broker is sent the annotations of the space and organization in which the service instance resides. When a service binding is being created, the service broker is sent annotations of any associated app, and the space and organization in which the binding resides. Only annotations with a prefix (e.g. company.com/contacts) are sent to service brokers.


            Examples may include (but are not limited to):


            "contact info": "bob@example.com jane@example.com"

            "library versions": "Spring: 5.1, Redis Client: a184098. yaml parser: 38"

            "git-sha": "d56fe0367554ae5e878e37ed6c5b9a82f5995512"

            Annotation keys

            Annotation keys are made up of an (optional) prefix and name. If a prefix is present, it is separated from the name by a /. Prefixes are DNS names intended to enable namespacing of annotation keys.


            An annotation key prefix must adhere to the following restrictions:


            Length: 0-253 characters

            Allowed characters: a-z, A-Z, 0-9, -, and .; emojis cannot be used in keys

            DNS subdomain format (series of subdomain annotations separated by .)

            An annotation key name must adhere to the following restrictions:


            Length: 1-63 characters

            Allowed characters: a-z, A-Z, 0-9, -, _, and .; emojis cannot be used in keys

            Must begin and end with an alphanumeric character

            Annotation values

            Annotation values must adhere to the following restrictions:


            Length: 0-5000 unicode characters

            '
      description: 'Metadata is a JSON object that contains information about a resource. It includes the GUID of the resource, the time the resource was created, the time the resource was last updated, and links to the resource.

        Metadata is included in the response body of a request to retrieve a resource.

        '
    OrganizationList:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        resources:
          type: array
          items:
            $ref: '#/components/schemas/Organization'
      description: A paginated list of organizations
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      description: 'An error response will always return a list of error objects. Errors appear on the job resource for asynchronous operations.

        Clients should use the code and title fields for programmatically handling specific errors. The message in the detail field is subject to change over time.

        '
    Error:
      type: object
      properties:
        code:
          type: integer
          description: A numeric code for this error
        detail:
          type: string
          description: Detailed description of the error
        title:
          type: string
          description: Name of the error
    Relationship:
      type: object
      properties:
        guid:
          type: string
          format: uuid
          description: The GUID of the resource
    BaseSchema:
      type: object
      properties:
        guid:
          type: string
          format: uuid
          description: The unique identifier for the resource
        created_at:
          type: string
          format: date-time
          description: The ISO8601 compatible date and time when resource was created
        updated_at:
          type: string
          format: date-time
          description: The ISO8601 compatible date and time when resource was last updated
      description: 'A resource represents an individual object within the system, such as an app or a service. It is represented as a JSON object.

        A resource consists of several required resource fields and other attributes specific to the resource.

        See Resources and Experimental Resources for specific resources.

        '
  requestBodies:
    IsolationSegmentCreate:
      description: Isolation segment to create
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the isolation segment; isolation segment names must be unique across the entire system, and case is ignored when checking for uniqueness
              metadata:
                $ref: '#/components/schemas/Metadata'
            required:
            - name
          examples:
            default:
              summary: default
              value:
                name: my_segment
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    UnprocessableEntity:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    BadGateway:
      description: Bad Gateway
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
        text/html:
          schema:
            type: string
    ServiceUnavailable:
      description: Service Unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
  parameters:
    OrderBy:
      name: order_by
      in: query
      required: false
      schema:
        type: string
      description: 'Value to sort by. Defaults to ascending; prepend with `-` to sort descending.

        '
      example: created_at
    CreatedAts:
      name: created_ats
      in: query
      required: false
      schema:
        type: string
      description: 'Timestamp to filter by. When filtering on equality, several comma-delimited timestamps may be passed. Also supports filtering with [relational operators](#relational-operators).

        '
      example: '2021-01-01T00:00:00Z'
    PerPage:
      name: per_page
      in: query
      required: false
      schema:
        type: integer
      description: Number of results per page, valid values are 1 through 5000
      example: 50
    LabelSelector:
      name: label_selector
      in: query
      description: A query string containing a list of [label selector](#labels-and-selectors) requirements
      required: false
      schema:
        type: string
      example: environment=production
    Page:
      name: page
      in: query
      required: false
      schema:
        type: integer
      description: Page to display; valid values are integers >= 1
      example: 1
    UpdatedAts:
      name: updated_ats
      in: query
      required: false
      schema:
        type: string
      description: 'Timestamp to filter by. When filtering on equality, several comma-delimited timestamps may be passed. Also supports filtering with [relational operators](#relational-operators).

        '
      example: '2021-01-01T00:00:00Z'
    Guid:
      name: guid
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: The unique identifier for the resource
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://uaa.cloudfoundry.local/api-oauth/dialog
          scopes:
            cloud_controller.admin: This scope provides read and write access to all resources
            cloud_controller.admin_read_only: This scope provides read only access to all resources
            cloud_controller.global_auditor: This scope provides read access to all resources
            cloud_controller.read: Read access to the Cloud Controller
            cloud_controller.write: Write access to the Cloud Controller
            cloud_controller.update_build_state: This scope allows its bearer to update the state of a build; currently only used when updating builds
            cloud_controller_service_permissions.read: This scope provides read only access for service instance permissions
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearer JWT token authentication
