openapi: 3.2.0
info:
  title: Cloud Foundry V3 Builds API
  description: '# Welcome to the Experimental Cloud Foundry V3 API Docs!'
  version: latest
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Cloud Foundry
    url: https://www.cloudfoundry.org/
servers:
- url: https://api.example.local
  description: Cloud Foundry V3 API server
security:
- oauth:
  - cloud_controller.read
  - cloud_controller.write
tags:
- name: Builds
  description: Builds represent the process of staging an application package.
paths:
  /v3/builds:
    get:
      summary: List builds
      description: Retrieve all builds.
      operationId: listBuilds
      tags:
      - Builds
      parameters:
      - $ref: '#/components/parameters/Page'
      - $ref: '#/components/parameters/PerPage'
      - $ref: '#/components/parameters/OrderBy'
      - $ref: '#/components/parameters/CreatedAts'
      - $ref: '#/components/parameters/UpdatedAts'
      - $ref: '#/components/parameters/LabelSelector'
      - name: states
        in: query
        schema:
          type: array
          items:
            type: string
            enum:
            - STAGING
            - STAGED
            - FAILED
        description: Comma-delimited list of build states to filter by
      - name: app_guids
        in: query
        schema:
          type: array
          items:
            type: string
        description: Comma-delimited list of app GUIDs to filter by
      - name: package_guids
        in: query
        schema:
          type: array
          items:
            type: string
        description: Comma-delimited list of package GUIDs to filter by
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildList'
              examples:
                default:
                  summary: default
                  value:
                    pagination:
                      total_results: 1
                      total_pages: 1
                      first:
                        href: https://api.example.org?states=STAGING&page=1&per_page=2
                      last:
                        href: https://api.example.org?states=STAGING&page=1&per_page=2
                      next: null
                      previous: null
                    resources:
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                      created_at: '2016-03-28T23:39:34Z'
                      updated_at: '2016-06-08T16:41:26Z'
                      created_by:
                        guid: 123e4567-e89b-12d3-a456-426614174000
                        name: bill
                        email: bill@example.com
                      state: STAGING
                      staging_memory_in_mb: 1024
                      staging_disk_in_mb: 1024
                      staging_log_rate_limit_bytes_per_second: 1024
                      error: null
                      lifecycle:
                        type: buildpack
                        data:
                          buildpacks:
                          - ruby_buildpack
                          stack: cflinuxfs4
                      package:
                        guid: 123e4567-e89b-12d3-a456-426614174000
                      droplet: null
                      relationships:
                        app:
                          data:
                            guid: 123e4567-e89b-12d3-a456-426614174000
                      metadata:
                        labels: {}
                        annotations: {}
                      links:
                        self:
                          href: https://api.example.org/v3/builds/585bc3c1-3743-497d-88b0-403ad6b56d16
                        app:
                          href: https://api.example.org/v3/apps/7b34f1cf-7e73-428a-bb5a-8a17a8058396
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500'
        '502':
          $ref: '#/components/responses/BadGateway'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
    post:
      summary: Create a build
      description: Create a build.
      operationId: createBuild
      tags:
      - Builds
      requestBody:
        description: Build object that needs to be created
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                package:
                  $ref: '#/components/schemas/Relationship'
                lifecycle:
                  $ref: '#/components/schemas/Lifecycle'
                staging_memory_in_mb:
                  type: integer
                  description: Memory in MB allocated for staging of the build
                staging_disk_in_mb:
                  type: integer
                  description: Disk space in MB allocated for staging of the build
                staging_log_rate_limit_bytes_per_second:
                  type: integer
                  description: Log rate limit in bytes per second allocated for staging of the build
                metadata:
                  $ref: '#/components/schemas/Metadata'
              required:
              - package
              description: Request schema for creating a build
            examples:
              default:
                summary: default
                value:
                  package:
                    guid: 123e4567-e89b-12d3-a456-426614174000
      responses:
        '201':
          description: Successfully created build
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Build'
          links:
            app:
              operationId: getApp
              parameters:
                guid: $response.body#/relationships/app/data/guid
              description: Retrieve the app for this build
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /v3/builds/{guid}:
    get:
      summary: Get a build
      description: Retrieve a build.
      operationId: getBuild
      tags:
      - Builds
      parameters:
      - $ref: '#/components/parameters/Guid'
      responses:
        '200':
          description: Successfully retrieved build
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Build'
          links:
            app:
              operationId: getApp
              parameters:
                guid: $response.body#/relationships/app/data/guid
              description: Retrieve the app for this build
            droplet:
              operationId: getDroplet
              parameters:
                guid: $response.body#/droplet/guid
              description: Retrieve the droplet for this build
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      summary: Update a build
      description: Update a build.
      operationId: updateBuild
      tags:
      - Builds
      parameters:
      - $ref: '#/components/parameters/Guid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuildUpdate'
            examples:
              default:
                summary: default
                value:
                  metadata:
                    labels:
                      key: value
                    annotations:
                      note: detailed information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Build'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /v3/apps/{guid}/builds:
    get:
      summary: List builds for an app
      description: Retrieve all builds for an app.
      operationId: listAppBuilds
      tags:
      - Builds
      parameters:
      - $ref: '#/components/parameters/Guid'
      - $ref: '#/components/parameters/Page'
      - $ref: '#/components/parameters/PerPage'
      - $ref: '#/components/parameters/OrderBy'
      - name: states
        in: query
        schema:
          type: array
          items:
            type: string
            enum:
            - STAGING
            - STAGED
            - FAILED
        description: Comma-delimited list of build states to filter by
      - $ref: '#/components/parameters/LabelSelector'
      - $ref: '#/components/parameters/CreatedAts'
      - $ref: '#/components/parameters/UpdatedAts'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildList'
              examples:
                default:
                  summary: default
                  value:
                    pagination:
                      total_results: 1
                      total_pages: 1
                      first:
                        href: https://api.example.org?states=STAGING&page=1&per_page=2
                      last:
                        href: https://api.example.org?states=STAGING&page=1&per_page=2
                      next: null
                      previous: null
                    resources:
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                      created_at: '2016-03-28T23:39:34Z'
                      updated_at: '2016-06-08T16:41:26Z'
                      created_by:
                        guid: 123e4567-e89b-12d3-a456-426614174000
                        name: bill
                        email: bill@example.com
                      state: STAGING
                      staging_memory_in_mb: 1024
                      staging_disk_in_mb: 1024
                      staging_log_rate_limit_bytes_per_second: 1024
                      error: null
                      lifecycle:
                        type: buildpack
                        data:
                          buildpacks:
                          - ruby_buildpack
                          stack: cflinuxfs4
                      package:
                        guid: 123e4567-e89b-12d3-a456-426614174000
                      droplet: null
                      relationships:
                        app:
                          data:
                            guid: 123e4567-e89b-12d3-a456-426614174000
                      metadata:
                        labels: {}
                        annotations: {}
                      links:
                        self:
                          href: https://api.example.org/v3/builds/585bc3c1-3743-497d-88b0-403ad6b56d16
                        app:
                          href: https://api.example.org/v3/apps/7b34f1cf-7e73-428a-bb5a-8a17a8058396
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      summary: Update a build
      description: Update a build.
      operationId: updateBuildViaApp
      tags:
      - Builds
      parameters:
      - $ref: '#/components/parameters/Guid'
      requestBody:
        description: Build object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                metadata:
                  $ref: '#/components/schemas/Metadata'
              description: Request schema for updating a build
      responses:
        '200':
          description: Successfully updated build
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Build'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
components:
  parameters:
    CreatedAts:
      name: created_ats
      in: query
      required: false
      schema:
        type: string
      description: 'Timestamp to filter by. When filtering on equality, several comma-delimited timestamps may be passed. Also supports filtering with [relational operators](#relational-operators).

        '
      example: '2021-01-01T00:00:00Z'
    Page:
      name: page
      in: query
      required: false
      schema:
        type: integer
      description: Page to display; valid values are integers >= 1
      example: 1
    Guid:
      name: guid
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: The unique identifier for the resource
    PerPage:
      name: per_page
      in: query
      required: false
      schema:
        type: integer
      description: Number of results per page, valid values are 1 through 5000
      example: 50
    OrderBy:
      name: order_by
      in: query
      required: false
      schema:
        type: string
      description: 'Value to sort by. Defaults to ascending; prepend with `-` to sort descending.

        '
      example: created_at
    LabelSelector:
      name: label_selector
      in: query
      description: A query string containing a list of [label selector](#labels-and-selectors) requirements
      required: false
      schema:
        type: string
      example: environment=production
    UpdatedAts:
      name: updated_ats
      in: query
      required: false
      schema:
        type: string
      description: 'Timestamp to filter by. When filtering on equality, several comma-delimited timestamps may be passed. Also supports filtering with [relational operators](#relational-operators).

        '
      example: '2021-01-01T00:00:00Z'
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          description: A numeric code for this error
        detail:
          type: string
          description: Detailed description of the error
        title:
          type: string
          description: Name of the error
    Pagination:
      type: object
      properties:
        total_results:
          type: integer
          description: The total number of results available
        total_pages:
          type: integer
          description: The total number of pages available
        first:
          allOf:
          - $ref: '#/components/schemas/Link'
          - description: The first page of results
        last:
          allOf:
          - $ref: '#/components/schemas/Link'
          - description: The last page of results
        next:
          oneOf:
          - $ref: '#/components/schemas/Link'
          - type: 'null'
          description: The next page of results
        previous:
          oneOf:
          - $ref: '#/components/schemas/Link'
          - type: 'null'
          description: The previous page of results
      description: 'Pagination is a technique used to divide a large set of results into smaller, more manageable sets. This allows clients to retrieve results in smaller chunks, reducing the amount of data transferred and improving performance.

        The pagination object is a JSON object that contains information about the pagination state of the results. It includes the total number of results available, the total number of pages available, and links to the first, last, next, and previous pages of results.

        '
    Build:
      type: object
      allOf:
      - $ref: '#/components/schemas/BaseSchema'
      - properties:
          state:
            type: string
            description: State of the build
            enum:
            - STAGING
            - STAGED
            - FAILED
          staging_memory_in_mb:
            type:
            - integer
            - 'null'
            description: Memory in MB allocated for staging of the build
          staging_disk_in_mb:
            type:
            - integer
            - 'null'
            description: Disk space in MB allocated for staging of the build
          staging_log_rate_limit_bytes_per_second:
            type: integer
            description: Log rate limit in bytes per second allocated for staging of the build
          error:
            type:
            - string
            - 'null'
            description: A string describing errors during the build process
          lifecycle:
            $ref: '#/components/schemas/Lifecycle'
            description: Provides the lifecycle object to use during staging; this will override the build’s application’s default lifecycle for this build
          checksum:
            type: object
            properties:
              type:
                type: string
                description: Hashing algorithm for checksum; supported algorithms are sha256 and sha1
              value:
                type: string
                description: Checksum of build
          metadata:
            $ref: '#/components/schemas/Metadata'
          relationships:
            $ref: '#/components/schemas/Relationships'
          package:
            type: object
            properties:
              guid:
                type: string
                format: uuid
            description: The package that is the input to the staging process
          droplet:
            type:
            - object
            - 'null'
            properties:
              guid:
                type: string
                format: uuid
            description: A resulting droplet from the staging process; `droplet` will be `null` if staging has not completed
          created_by:
            type: object
            properties:
              guid:
                type: string
                description: The guid of the user that created the build
              name:
                type:
                - string
                - 'null'
                description: The name of the user that created the build
              email:
                type:
                - string
                - 'null'
                description: The email of the user that created the build
          links:
            type: object
            properties:
              self:
                $ref: '#/components/schemas/Link'
                description: The URL to get this build
              app:
                $ref: '#/components/schemas/Link'
                description: The URL to get the app for this build
              droplet:
                $ref: '#/components/schemas/Link'
                description: The URL to get the droplet for this build
      description: 'Builds represent the process of transforming source code into a runnable artifact. Builds can be triggered manually or automatically as part of the app lifecycle. A successful build results in a droplet that can be used to run the app.

        '
    BuildUpdate:
      type: object
      properties:
        state:
          type: string
          description: State of the build
          enum:
          - STAGING
          - STAGED
          - FAILED
        staging_memory_in_mb:
          type:
          - integer
          - 'null'
          description: Memory in MB allocated for staging of the build
        staging_disk_in_mb:
          type:
          - integer
          - 'null'
          description: Disk space in MB allocated for staging of the build
        staging_log_rate_limit_bytes_per_second:
          type: integer
          description: Log rate limit in bytes per second allocated for staging of the build
        error:
          type:
          - string
          - 'null'
          description: A string describing errors during the build process
        lifecycle:
          $ref: '#/components/schemas/Lifecycle'
          description: Provides the lifecycle object to use during staging
        metadata:
          $ref: '#/components/schemas/Metadata'
    Link:
      type: object
      properties:
        href:
          type: string
          description: The URL of the link
        method:
          type: string
          description: An optional field containing the HTTP method to be used when following the URL
      required:
      - href
      description: 'Each link is keyed by its type and will include a href for the URL and an optional method for links that cannot be followed using GET.

        '
    Metadata:
      type: object
      properties:
        labels:
          type: object
          additionalProperties:
            type:
            - string
            - 'null'
          description: 'A set of key-value pairs that describe the resource. Labels are a JSON object that contains information about a resource. They are used to tag resources with metadata that can be used to filter and group resources. Labels are included in the response body of a request to retrieve a resource.

            Labels are user-specified key/value pairs that are attached to API Resources. They are queryable, identifying attributes of a resource, but they do not affect the operation of CloudFoundry.


            For example, an app may be assigned a label with key sensitive and possible values true or false.


            Users could then find all sensitive apps with a selector for sensitive=true, resulting in a response containing only apps having the label key sensitive with a label value of true.


            Labels

            Labels allow users to apply identifying attributes to resources that are meaningful to the user, but not the CloudFoundry system.


            Examples may include (but are not limited to):


            "production" : "true" or "production" : "false"

            "env" : "dev" or "env" : "test" or "env" : "prod"

            "chargeback-code" : "abc123"

            Label keys

            Label keys are made up of an (optional) prefix, and name. If a prefix is present, it is separated from the name by a /. Prefixes are dns names intended to enable namespacing of label keys.


            A label key prefix must adhere to the following restrictions:


            Length: 0-253 characters

            Allowed characters: alphanumeric ( [a-z0-9A-Z] ), -, and .

            DNS subdomain format (series of subdomain labels separated by .)

            A label key name must adhere to the following restrictions:


            Length: 1-63 characters

            Allowed characters: alphanumeric ( [a-z0-9A-Z] ), -, _, and .

            Must begin and end with an alphanumeric character

            Label values

            Label values must adhere to the following restrictions:


            Length: 0-63 characters

            Allowed characters: alphanumeric ( [a-z0-9A-Z] ), -, _, and .

            Must begin and end with an alphanumeric character

            Empty values are allowed

            '
        annotations:
          type: object
          additionalProperties:
            type:
            - string
            - 'null'
          description: 'A set of key-value pairs that describe the resource. Annotations are a JSON object that contains information about a resource. They are used to tag resources with metadata that can be used to filter and group resources. Annotations are included in the response body of a request to retrieve a resource.

            Annotations are user-specified key-value pairs that are attached to API resources. They do not affect the operation of Cloud Foundry. Annotations cannot be used in filters.


            When a service instance is being created, the service broker is sent the annotations of the service instance, and the space and organization in which the service instance resides. When a service instance is being updated, the service broker is sent the annotations of the space and organization in which the service instance resides. When a service binding is being created, the service broker is sent annotations of any associated app, and the space and organization in which the binding resides. Only annotations with a prefix (e.g. company.com/contacts) are sent to service brokers.


            Examples may include (but are not limited to):


            "contact info": "bob@example.com jane@example.com"

            "library versions": "Spring: 5.1, Redis Client: a184098. yaml parser: 38"

            "git-sha": "d56fe0367554ae5e878e37ed6c5b9a82f5995512"

            Annotation keys

            Annotation keys are made up of an (optional) prefix and name. If a prefix is present, it is separated from the name by a /. Prefixes are DNS names intended to enable namespacing of annotation keys.


            An annotation key prefix must adhere to the following restrictions:


            Length: 0-253 characters

            Allowed characters: a-z, A-Z, 0-9, -, and .; emojis cannot be used in keys

            DNS subdomain format (series of subdomain annotations separated by .)

            An annotation key name must adhere to the following restrictions:


            Length: 1-63 characters

            Allowed characters: a-z, A-Z, 0-9, -, _, and .; emojis cannot be used in keys

            Must begin and end with an alphanumeric character

            Annotation values

            Annotation values must adhere to the following restrictions:


            Length: 0-5000 unicode characters

            '
      description: 'Metadata is a JSON object that contains information about a resource. It includes the GUID of the resource, the time the resource was created, the time the resource was last updated, and links to the resource.

        Metadata is included in the response body of a request to retrieve a resource.

        '
    Relationships:
      type: object
      description: 'Relationships represent associations between resources. When relationships are mutable, they can be used to create, read, update, and delete these associations. An app’s relationship to its current droplet is mutable, but an app’s relationship to its space is not.


        Relationships do not affect the fundamental properties of a resource, but may affect their behavior and permissions logic. Relationships are tied to the lifecycles of the associated resources and will be removed if either of the associated resources are deleted. For example, if a user is removed from an organization, both the user and the organization persist, but the relationship between them does not.


        Not all resources implement every relationship operation demonstrated in the examples below. See the docs for each resource to see how it interacts with its relationships.


        Endpoints that return relationship data list this information under the relationships key.


        The relationship object

        The relationship object is a key-value pair that uniquely identifies a resource. In practice this is almost always the guid of a resource.

        '
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      description: 'An error response will always return a list of error objects. Errors appear on the job resource for asynchronous operations.

        Clients should use the code and title fields for programmatically handling specific errors. The message in the detail field is subject to change over time.

        '
    Lifecycle:
      type: object
      properties:
        type:
          type: string
          description: Type of the lifecycle; valid values are buildpack, cnb, docker
        data:
          type: object
          additionalProperties: true
          description: Data specific to the lifecycle
          properties:
            buildpacks:
              type: array
              items:
                type: string
              description: List of the names of buildpacks, URLs from which they may be downloaded, or null to auto-detect a suitable buildpack during staging (applicable for buildpack and cnb lifecycles)
            stack:
              type:
              - string
              - 'null'
              description: The root filesystem to use with the buildpack, for example cflinuxfs4 (applicable for buildpack lifecycle)
            credentials:
              type: object
              additionalProperties:
                type: object
                properties:
                  username:
                    type:
                    - string
                    - 'null'
                  password:
                    type:
                    - string
                    - 'null'
                  token:
                    type: string
              description: Credentials used to download the configured buildpacks (applicable for cnb lifecycle)
      description: 'The lifecycle type defines how the application droplet is created and run. The following lifecycle types are supported: - buildpack: Traditional buildpacks for Cloud Foundry applications. - cnb: Cloud Native Buildpacks that are OCI-compliant. - docker: Run pre-built Docker images.

        '
    BaseSchema:
      type: object
      properties:
        guid:
          type: string
          format: uuid
          description: The unique identifier for the resource
        created_at:
          type: string
          format: date-time
          description: The ISO8601 compatible date and time when resource was created
        updated_at:
          type: string
          format: date-time
          description: The ISO8601 compatible date and time when resource was last updated
      description: 'A resource represents an individual object within the system, such as an app or a service. It is represented as a JSON object.

        A resource consists of several required resource fields and other attributes specific to the resource.

        See Resources and Experimental Resources for specific resources.

        '
    Relationship:
      type: object
      properties:
        guid:
          type: string
          format: uuid
          description: The GUID of the resource
    BuildList:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        resources:
          type: array
          items:
            $ref: '#/components/schemas/Build'
  responses:
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    BadGateway:
      description: Bad Gateway
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    ServiceUnavailable:
      description: Service Unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    UnprocessableEntity:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
        text/html:
          schema:
            type: string
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://uaa.cloudfoundry.local/api-oauth/dialog
          scopes:
            cloud_controller.admin: This scope provides read and write access to all resources
            cloud_controller.admin_read_only: This scope provides read only access to all resources
            cloud_controller.global_auditor: This scope provides read access to all resources
            cloud_controller.read: Read access to the Cloud Controller
            cloud_controller.write: Write access to the Cloud Controller
            cloud_controller.update_build_state: This scope allows its bearer to update the state of a build; currently only used when updating builds
            cloud_controller_service_permissions.read: This scope provides read only access for service instance permissions
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearer JWT token authentication
