openapi: 3.2.0
info:
  title: Cloud Foundry V3 Service Brokers API
  description: '# Welcome to the Experimental Cloud Foundry V3 API Docs!'
  version: latest
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Cloud Foundry
    url: https://www.cloudfoundry.org/
servers:
- url: https://api.example.local
  description: Cloud Foundry V3 API server
security:
- oauth:
  - cloud_controller.read
  - cloud_controller.write
tags:
- name: Service Brokers
  description: Service brokers are used to manage services.
paths:
  /v3/service_brokers:
    get:
      summary: List service brokers
      description: This endpoint retrieves the service brokers the user has access to.
      operationId: listServiceBrokers
      tags:
      - Service Brokers
      parameters:
      - $ref: '#/components/parameters/Page'
      - $ref: '#/components/parameters/PerPage'
      - $ref: '#/components/parameters/OrderBy'
      - name: names
        in: query
        schema:
          type: array
          items:
            type: string
        description: Comma-delimited list of service broker names to filter by
      - name: space_guids
        in: query
        schema:
          type: array
          items:
            type: string
        description: Comma-delimited list of space guids to filter by
      - $ref: '#/components/parameters/LabelSelector'
      - $ref: '#/components/parameters/CreatedAts'
      - $ref: '#/components/parameters/UpdatedAts'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceBrokerList'
              examples:
                default:
                  summary: default
                  value:
                    pagination:
                      total_results: 3
                      total_pages: 2
                      first:
                        href: https://api.example.org?page=1&per_page=2
                      last:
                        href: https://api.example.org?page=2&per_page=2
                      next:
                        href: https://api.example.org?page=2&per_page=2
                      previous: null
                    resources:
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                      name: my_service_broker
                      url: https://example.service-broker.com
                      created_at: '2015-11-13T17:02:56Z'
                      updated_at: '2016-06-08T16:41:26Z'
                      relationships: {}
                      metadata:
                        labels: {}
                        annotations: {}
                      links:
                        self:
                          href: https://api.example.org/v3/service_brokers/dde5ad2a-d8f4-44dc-a56f-0452d744f1c3
                        service_offerings:
                          href: https://api.example.org/v3/service_offerings?service_broker_guids=dde5ad2a-d8f4-44dc-a56f-0452d744f1c3
                    - guid: 123e4567-e89b-12d3-a456-426614174000
                      name: another_service_broker
                      url: https://another-example.service-broker.com
                      created_at: '2015-11-13T17:02:56Z'
                      updated_at: '2016-06-08T16:41:26Z'
                      relationships:
                        space:
                          data:
                            guid: 123e4567-e89b-12d3-a456-426614174000
                      metadata:
                        labels: {}
                        annotations: {}
                      links:
                        self:
                          href: https://api.example.org/v3/service_brokers/7aa37bad-6ccb-4ef9-ba48-9ce3a91b2b62
                        service_offerings:
                          href: https://api.example.org/v3/service_offerings?service_broker_guids=7aa37bad-6ccb-4ef9-ba48-9ce3a91b2b62
                        space:
                          href: https://api.example.org/v3/spaces/2f35885d-0c9d-4423-83ad-fd05066f8576
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500'
        '502':
          $ref: '#/components/responses/BadGateway'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
    post:
      summary: Create a service broker
      description: This endpoint creates a new service broker and a job to synchronize the service offerings and service plans with those in the broker’s catalog. The `Location` header refers to the created job which syncs the broker with the catalog. See _Service broker jobs_ for more information and limitations.
      operationId: createServiceBroker
      tags:
      - Service Brokers
      requestBody:
        $ref: '#/components/requestBodies/ServiceBrokerCreate'
      responses:
        '202':
          description: Accepted
          headers:
            Location:
              description: URL of the job that is creating the service broker
              schema:
                type: string
                format: uri
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /v3/service_brokers/{guid}:
    get:
      summary: Get a service broker
      description: This endpoint retrieves the service broker by GUID.
      operationId: getServiceBroker
      tags:
      - Service Brokers
      parameters:
      - $ref: '#/components/parameters/Guid'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceBroker'
              examples:
                default:
                  summary: default
                  value:
                    guid: 123e4567-e89b-12d3-a456-426614174000
                    name: my_service_broker
                    url: https://example.service-broker.com
                    created_at: '2015-11-13T17:02:56Z'
                    updated_at: '2016-06-08T16:41:26Z'
                    relationships:
                      space:
                        data:
                          guid: 123e4567-e89b-12d3-a456-426614174000
                    metadata:
                      labels:
                        type: dev
                      annotations: {}
                    links:
                      self:
                        href: https://api.example.org/v3/service_brokers/dde5ad2a-d8f4-44dc-a56f-0452d744f1c3
                      service_offerings:
                        href: https://api.example.org/v3/service_offerings?service_broker_guids=dde5ad2a-d8f4-44dc-a56f-0452d744f1c3
                      space:
                        href: https://api.example.org/v3/spaces/2f35885d-0c9d-4423-83ad-fd05066f8576
          links:
            space:
              operationId: getSpace
              parameters:
                guid: $response.body#/relationships/space/data/guid
              description: Retrieve the space for this service broker (space-scoped brokers only)
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      summary: Update a service broker
      description: 'This endpoint updates a service broker. Depending on the parameters specified, the endpoint may respond with a background job, and it may synchronize the service offerings and service plans with those in the broker’s catalog.


        When a service broker has a synchronization job in progress, only updates with `metadata` are permitted until the synchronization job is complete.'
      operationId: updateServiceBroker
      tags:
      - Service Brokers
      parameters:
      - $ref: '#/components/parameters/Guid'
      requestBody:
        $ref: '#/components/requestBodies/ServiceBrokerUpdateRequestBody'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceBroker'
              examples:
                default:
                  summary: default
                  value:
                    guid: 123e4567-e89b-12d3-a456-426614174000
                    name: my_service_broker
                    url: https://example.service-broker.com
                    created_at: '2015-11-13T17:02:56Z'
                    updated_at: '2016-06-08T16:41:26Z'
                    relationships:
                      space:
                        data:
                          guid: 123e4567-e89b-12d3-a456-426614174000
                    metadata:
                      labels:
                        type: dev
                      annotations: {}
                    links:
                      self:
                        href: https://api.example.org/v3/service_brokers/dde5ad2a-d8f4-44dc-a56f-0452d744f1c3
                      service_offerings:
                        href: https://api.example.org/v3/service_offerings?service_broker_guids=dde5ad2a-d8f4-44dc-a56f-0452d744f1c3
                      space:
                        href: https://api.example.org/v3/spaces/2f35885d-0c9d-4423-83ad-fd05066f8576
          links:
            space:
              operationId: getSpace
              parameters:
                guid: $response.body#/relationships/space/data/guid
              description: Retrieve the space for this service broker (space-scoped brokers only)
        '202':
          description: Accepted
          headers:
            Location:
              description: URL of the job that is updating the service broker
              schema:
                type: string
                format: uri
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
    delete:
      summary: Delete a service broker
      description: This endpoint creates a job to delete an existing service broker. The `Location` header refers to the created job. See _Service broker jobs_ for more information and limitations.
      operationId: deleteServiceBroker
      tags:
      - Service Brokers
      parameters:
      - $ref: '#/components/parameters/Guid'
      responses:
        '202':
          description: Accepted
          headers:
            Location:
              description: URL of the job that is deleting the service broker
              schema:
                type: string
                format: uri
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500'
components:
  requestBodies:
    ServiceBrokerCreate:
      description: Service broker to create
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the service broker
              url:
                type: string
                format: uri
                description: URL of the service broker
              authentication:
                type: object
                properties:
                  type:
                    type: string
                    enum:
                    - basic
                    description: Type of authentication
                  credentials:
                    type: object
                    properties:
                      username:
                        type: string
                      password:
                        type: string
                    required:
                    - username
                    - password
                required:
                - type
                - credentials
                description: Authentication details for the service broker
              relationships:
                type: object
                properties:
                  space:
                    $ref: '#/components/schemas/RelationshipToOne'
                description: Relationships for the service broker
              metadata:
                $ref: '#/components/schemas/Metadata'
            required:
            - name
            - url
          examples:
            default:
              summary: default
              value:
                name: my_service_broker
                url: https://example.service-broker.com
                authentication:
                  type: basic
                  credentials:
                    username: us3rn4me
                    password: p4ssw0rd
                relationships:
                  space:
                    data:
                      guid: 123e4567-e89b-12d3-a456-426614174000
    ServiceBrokerUpdateRequestBody:
      description: Service broker object that needs to be updated
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the service broker
              url:
                type: string
                description: URL of the service broker
              authentication:
                type: object
                description: Credentials used to authenticate against the service broker
                properties:
                  type:
                    type: string
                    enum:
                    - basic
                    description: Authentication type
                  credentials:
                    type: object
                    description: Authentication credentials
                    properties:
                      username:
                        type: string
                        description: Username for basic authentication
                      password:
                        type: string
                        description: Password for basic authentication
                    required:
                    - username
                    - password
                required:
                - type
                - credentials
              metadata:
                $ref: '#/components/schemas/Metadata'
          examples:
            default:
              summary: default
              value:
                name: my_service_broker
                url: https://example.service-broker.com
                authentication:
                  type: basic
                  credentials:
                    username: us3rn4me
                    password: p4ssw0rd
                metadata:
                  labels:
                    key: value
                  annotations:
                    note: detailed information
  schemas:
    Pagination:
      type: object
      properties:
        total_results:
          type: integer
          description: The total number of results available
        total_pages:
          type: integer
          description: The total number of pages available
        first:
          allOf:
          - $ref: '#/components/schemas/Link'
          - description: The first page of results
        last:
          allOf:
          - $ref: '#/components/schemas/Link'
          - description: The last page of results
        next:
          oneOf:
          - $ref: '#/components/schemas/Link'
          - type: 'null'
          description: The next page of results
        previous:
          oneOf:
          - $ref: '#/components/schemas/Link'
          - type: 'null'
          description: The previous page of results
      description: 'Pagination is a technique used to divide a large set of results into smaller, more manageable sets. This allows clients to retrieve results in smaller chunks, reducing the amount of data transferred and improving performance.

        The pagination object is a JSON object that contains information about the pagination state of the results. It includes the total number of results available, the total number of pages available, and links to the first, last, next, and previous pages of results.

        '
    Link:
      type: object
      properties:
        href:
          type: string
          description: The URL of the link
        method:
          type: string
          description: An optional field containing the HTTP method to be used when following the URL
      required:
      - href
      description: 'Each link is keyed by its type and will include a href for the URL and an optional method for links that cannot be followed using GET.

        '
    RelationshipToOne:
      type: object
      properties:
        data:
          type:
          - object
          - 'null'
          $ref: '#/components/schemas/Relationship'
        links:
          type: object
          properties:
            self:
              $ref: '#/components/schemas/Link'
            related:
              $ref: '#/components/schemas/Link'
      description: 'Some relationships relate a resource to exactly one other resource. For example an app can belong to only one space.

        '
    Metadata:
      type: object
      properties:
        labels:
          type: object
          additionalProperties:
            type:
            - string
            - 'null'
          description: 'A set of key-value pairs that describe the resource. Labels are a JSON object that contains information about a resource. They are used to tag resources with metadata that can be used to filter and group resources. Labels are included in the response body of a request to retrieve a resource.

            Labels are user-specified key/value pairs that are attached to API Resources. They are queryable, identifying attributes of a resource, but they do not affect the operation of CloudFoundry.


            For example, an app may be assigned a label with key sensitive and possible values true or false.


            Users could then find all sensitive apps with a selector for sensitive=true, resulting in a response containing only apps having the label key sensitive with a label value of true.


            Labels

            Labels allow users to apply identifying attributes to resources that are meaningful to the user, but not the CloudFoundry system.


            Examples may include (but are not limited to):


            "production" : "true" or "production" : "false"

            "env" : "dev" or "env" : "test" or "env" : "prod"

            "chargeback-code" : "abc123"

            Label keys

            Label keys are made up of an (optional) prefix, and name. If a prefix is present, it is separated from the name by a /. Prefixes are dns names intended to enable namespacing of label keys.


            A label key prefix must adhere to the following restrictions:


            Length: 0-253 characters

            Allowed characters: alphanumeric ( [a-z0-9A-Z] ), -, and .

            DNS subdomain format (series of subdomain labels separated by .)

            A label key name must adhere to the following restrictions:


            Length: 1-63 characters

            Allowed characters: alphanumeric ( [a-z0-9A-Z] ), -, _, and .

            Must begin and end with an alphanumeric character

            Label values

            Label values must adhere to the following restrictions:


            Length: 0-63 characters

            Allowed characters: alphanumeric ( [a-z0-9A-Z] ), -, _, and .

            Must begin and end with an alphanumeric character

            Empty values are allowed

            '
        annotations:
          type: object
          additionalProperties:
            type:
            - string
            - 'null'
          description: 'A set of key-value pairs that describe the resource. Annotations are a JSON object that contains information about a resource. They are used to tag resources with metadata that can be used to filter and group resources. Annotations are included in the response body of a request to retrieve a resource.

            Annotations are user-specified key-value pairs that are attached to API resources. They do not affect the operation of Cloud Foundry. Annotations cannot be used in filters.


            When a service instance is being created, the service broker is sent the annotations of the service instance, and the space and organization in which the service instance resides. When a service instance is being updated, the service broker is sent the annotations of the space and organization in which the service instance resides. When a service binding is being created, the service broker is sent annotations of any associated app, and the space and organization in which the binding resides. Only annotations with a prefix (e.g. company.com/contacts) are sent to service brokers.


            Examples may include (but are not limited to):


            "contact info": "bob@example.com jane@example.com"

            "library versions": "Spring: 5.1, Redis Client: a184098. yaml parser: 38"

            "git-sha": "d56fe0367554ae5e878e37ed6c5b9a82f5995512"

            Annotation keys

            Annotation keys are made up of an (optional) prefix and name. If a prefix is present, it is separated from the name by a /. Prefixes are DNS names intended to enable namespacing of annotation keys.


            An annotation key prefix must adhere to the following restrictions:


            Length: 0-253 characters

            Allowed characters: a-z, A-Z, 0-9, -, and .; emojis cannot be used in keys

            DNS subdomain format (series of subdomain annotations separated by .)

            An annotation key name must adhere to the following restrictions:


            Length: 1-63 characters

            Allowed characters: a-z, A-Z, 0-9, -, _, and .; emojis cannot be used in keys

            Must begin and end with an alphanumeric character

            Annotation values

            Annotation values must adhere to the following restrictions:


            Length: 0-5000 unicode characters

            '
      description: 'Metadata is a JSON object that contains information about a resource. It includes the GUID of the resource, the time the resource was created, the time the resource was last updated, and links to the resource.

        Metadata is included in the response body of a request to retrieve a resource.

        '
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      description: 'An error response will always return a list of error objects. Errors appear on the job resource for asynchronous operations.

        Clients should use the code and title fields for programmatically handling specific errors. The message in the detail field is subject to change over time.

        '
    ServiceBrokerList:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        resources:
          type: array
          items:
            $ref: '#/components/schemas/ServiceBroker'
    ServiceBroker:
      type: object
      allOf:
      - $ref: '#/components/schemas/BaseSchema'
      - properties:
          name:
            type: string
            description: Name of the service broker
          url:
            type: string
            format: uri
            description: URL of the service broker
          relationships:
            type: object
            properties:
              space:
                $ref: '#/components/schemas/RelationshipToOne'
            description: Relationships for the service broker
          links:
            type: object
            properties:
              self:
                $ref: '#/components/schemas/Link'
              space:
                $ref: '#/components/schemas/Link'
              service_offerings:
                $ref: '#/components/schemas/Link'
          metadata:
            $ref: '#/components/schemas/Metadata'
        required:
        - name
        - url
        - links
    Error:
      type: object
      properties:
        code:
          type: integer
          description: A numeric code for this error
        detail:
          type: string
          description: Detailed description of the error
        title:
          type: string
          description: Name of the error
    Relationship:
      type: object
      properties:
        guid:
          type: string
          format: uuid
          description: The GUID of the resource
    BaseSchema:
      type: object
      properties:
        guid:
          type: string
          format: uuid
          description: The unique identifier for the resource
        created_at:
          type: string
          format: date-time
          description: The ISO8601 compatible date and time when resource was created
        updated_at:
          type: string
          format: date-time
          description: The ISO8601 compatible date and time when resource was last updated
      description: 'A resource represents an individual object within the system, such as an app or a service. It is represented as a JSON object.

        A resource consists of several required resource fields and other attributes specific to the resource.

        See Resources and Experimental Resources for specific resources.

        '
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    UnprocessableEntity:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    BadGateway:
      description: Bad Gateway
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
        text/html:
          schema:
            type: string
    ServiceUnavailable:
      description: Service Unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
  parameters:
    OrderBy:
      name: order_by
      in: query
      required: false
      schema:
        type: string
      description: 'Value to sort by. Defaults to ascending; prepend with `-` to sort descending.

        '
      example: created_at
    CreatedAts:
      name: created_ats
      in: query
      required: false
      schema:
        type: string
      description: 'Timestamp to filter by. When filtering on equality, several comma-delimited timestamps may be passed. Also supports filtering with [relational operators](#relational-operators).

        '
      example: '2021-01-01T00:00:00Z'
    PerPage:
      name: per_page
      in: query
      required: false
      schema:
        type: integer
      description: Number of results per page, valid values are 1 through 5000
      example: 50
    LabelSelector:
      name: label_selector
      in: query
      description: A query string containing a list of [label selector](#labels-and-selectors) requirements
      required: false
      schema:
        type: string
      example: environment=production
    Page:
      name: page
      in: query
      required: false
      schema:
        type: integer
      description: Page to display; valid values are integers >= 1
      example: 1
    UpdatedAts:
      name: updated_ats
      in: query
      required: false
      schema:
        type: string
      description: 'Timestamp to filter by. When filtering on equality, several comma-delimited timestamps may be passed. Also supports filtering with [relational operators](#relational-operators).

        '
      example: '2021-01-01T00:00:00Z'
    Guid:
      name: guid
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: The unique identifier for the resource
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://uaa.cloudfoundry.local/api-oauth/dialog
          scopes:
            cloud_controller.admin: This scope provides read and write access to all resources
            cloud_controller.admin_read_only: This scope provides read only access to all resources
            cloud_controller.global_auditor: This scope provides read access to all resources
            cloud_controller.read: Read access to the Cloud Controller
            cloud_controller.write: Write access to the Cloud Controller
            cloud_controller.update_build_state: This scope allows its bearer to update the state of a build; currently only used when updating builds
            cloud_controller_service_permissions.read: This scope provides read only access for service instance permissions
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearer JWT token authentication
